name: dc_auth
version: 1.0.0
main: me.ownsample.dc_auth.dc_auth
description: Auth via discord
author: OwnSample
website: https://github.com/OwnSample-hash/dc_auth
api-version: '1.20'
commands:
  link:
    description: "Link your account"
    usage: /<command> id